//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodEntities : DbContext
    {
        public FoodEntities()
            : base("name=FoodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<FoodShare> FoodShare { get; set; }
        public virtual DbSet<FoodShareCollection> FoodShareCollection { get; set; }
        public virtual DbSet<FoodShareComment> FoodShareComment { get; set; }
        public virtual DbSet<FoodShareReply> FoodShareReply { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostCollection> PostCollection { get; set; }
        public virtual DbSet<PostComment> PostComment { get; set; }
        public virtual DbSet<PostReply> PostReply { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<VideoCollection> VideoCollection { get; set; }
        public virtual DbSet<VideoComment> VideoComment { get; set; }
        public virtual DbSet<VideoReply> VideoReply { get; set; }
    }
}
