//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostReply
    {
        public int PostReply_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> PostComment_id { get; set; }
        public Nullable<int> Post_id { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string PostReply_content { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual PostComment PostComment { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
