//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.PostCollection = new HashSet<PostCollection>();
            this.PostComment = new HashSet<PostComment>();
            this.PostReply = new HashSet<PostReply>();
        }
    
        public int Post_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Post_title { get; set; }
        public string Post_content { get; set; }
        public string Post_img { get; set; }
        public Nullable<System.DateTime> Post_addtime { get; set; }
        public string Post_lable { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<int> Collection { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostCollection> PostCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostComment> PostComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostReply> PostReply { get; set; }
    }
}
