//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodShare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodShare()
        {
            this.FoodShareCollection = new HashSet<FoodShareCollection>();
            this.FoodShareComment = new HashSet<FoodShareComment>();
            this.FoodShareReply = new HashSet<FoodShareReply>();
        }
    
        public int Fs_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Fs_title { get; set; }
        public string Fs_img { get; set; }
        public string Fs_lable { get; set; }
        public Nullable<System.DateTime> Fs_addtime { get; set; }
        public string Fs_detail { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<int> Collection { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodShareCollection> FoodShareCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodShareComment> FoodShareComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodShareReply> FoodShareReply { get; set; }
    }
}
