//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodShareComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodShareComment()
        {
            this.FoodShareReply = new HashSet<FoodShareReply>();
        }
    
        public int FsComment_id { get; set; }
        public string FsComment_content { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Fs_id { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
    
        public virtual FoodShare FoodShare { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodShareReply> FoodShareReply { get; set; }
    }
}
